apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: python-cvjkvzhl
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: tssc-quay-quay-tssc-quay.apps.cluster-gj92t.gj92t.sandbox3211.opentlc.com/tssc/python-cvjkvzhl:github-9eb3e1ee82957cbf326c8846bdfcdbfe07bbf71f
          name: container-image
